general:
  title: "Patrick Laing"
  description: "Patrick Laing is a London based product design studio crafting ranges of innovative of jewellery, industrial product, homeware and retail design."
  image: "patrick_laing.png"
  keywords: "patrick laing, industrial design, design, rings, product design, plume, mudguard"
  url: "https://patricklaing.com"
imagePath: "./assets/images/"
left:
  title: "Products"
  videos:
  - id: '1023226361'
  - id: '1023217032'
  - id: '1023232933'
  - id: '1022945795'
  images:
    - fileName: "EDITED_Patrick_Laing_Sketchbook_Two.jpg"
    - fileName: "EDITED_Patrick_Laing_Sketchbook.jpg"
      cover: true
    - fileName: "EDITED>Patrick_Laing_exhibition_stands_adidas_.jpg"
      cover: true
    - fileName: "EDITED>Patrick_Laing_store_shop_design_adidas_one.jpg"
      cover: true
    - fileName: "EDITED>Patrick_Laing_store_shop_design_adidas_two.jpg"
    - fileName: "Gold+winged+figure+trophy+design+face.jpg"
      cover: true
    - fileName: "Gold+Winged+Figure+Trophy+design+front.jpg"
      cover: true
    - fileName: "Gold+Winged+figure+trophy+design+rear.jpg"
      cover: true
    - fileName: "Making_2_Patrick_Laing_Film_Award.jpg"
    - fileName: "Making_3_Patrick_Laing_Film_Award.jpg"
      cover: true
    - fileName: "O2O2-Side-Large-Patrick-Laing.jpg"
      cover: true
    - fileName: "Pinhole_Making.jpg"
      cover: true
    - fileName: "Plume-Outdoor-Unfurl-Brick.jpg"
    - fileName: "SNV37449.jpg"
    - fileName: "The_Flying_Skirt_TEST.jpg"
    - fileName: "Trophy_scans_1.jpg"
      cover: true
    - fileName: "Trophy_scans_2.jpg"
      cover: true
    - fileName: "2of3_Socks_bed&couch.jpg"
    - fileName: "Adidias_shop_No.9_Patrick_Laing.jpg"
right:
  title: "Rings"
  videos:
    - id: '1023231801'
  images:
    - fileName: 'surface_0003.jpg'
    - fileName: 'surface_0002.jpg'
    - fileName: 'surface_0001.jpg'
    - fileName: 'surface_0000.jpg'

contact:
  linkText: "Contact"
  email: "patrick@patricklaing.com"

credits:
  -
    linkText: "Design by Ongoing Projects"
    linkDestination: "https://ongoingprojects.co"
  -
    linkText: "Built by Laura Brown"
    linkDestination: "https://laurabrown.xyz"

