general:
  title: "Patrick Laing"
  description: "Patrick Laing is a London based product design studio crafting ranges of innovative of jewellery, industrial product, homeware and retail design."
  image: "patrick_laing.png"
  keywords: "patrick laing, industrial design, design, rings, product design, plume, mudguard"
  url: "https://patricklaing.com"
imagePath: "../assets/images/"
left:
  title: "Products"
  videos:
    - 'https://player.vimeo.com/external/352805980.hd.mp4?s=598441d86cabeb3dd01f3c6687be6be7c95e71a4&profile_id=174'
    - 'https://player.vimeo.com/external/352804677.hd.mp4?s=718517eea76546bbe16954974175cc7229a671c0&profile_id=174'
    - 'https://player.vimeo.com/external/352803921.hd.mp4?s=2895814bb45f2fe13384fe46dd56e647b598e727&profile_id=174'
    - 'https://player.vimeo.com/external/352803209.hd.mp4?s=9eb67b52d10865b7774c31002b6e7a66b062c6b2&profile_id=174'
    - 'https://player.vimeo.com/external/352803182.hd.mp4?s=dcba7118e81eb3dfe67800506a9f1b323620a700&profile_id=174'
    - 'https://player.vimeo.com/external/352803100.hd.mp4?s=7e2024d407dde64072d5875be80d493d142df416&profile_id=174'
    - 'https://player.vimeo.com/external/352802822.hd.mp4?s=0fd2713812ee5cad6889bbc594e06a90f232a5b8&profile_id=174'
    - 'https://player.vimeo.com/external/350055495.hd.mp4?s=77485a32b2cdfeaa26fa5869cdf2032751ad1c10&profile_id=174'
  images:
    - fileName: "EDITED_Patrick_Laing_Sketchbook_Two.jpg"
    - fileName: "EDITED_Patrick_Laing_Sketchbook.jpg"
      cover: true
    - fileName: "EDITED>Patrick_Laing_exhibition_stands_adidas_.jpg"
      cover: true
    - fileName: "EDITED>Patrick_Laing_store_shop_design_adidas_one.jpg"
      cover: true
    - fileName: "EDITED>Patrick_Laing_store_shop_design_adidas_two.jpg"
    - fileName: "Gold+winged+figure+trophy+design+face.jpg"
      cover: true
    - fileName: "Gold+Winged+Figure+Trophy+design+front.jpg"
      cover: true
    - fileName: "Gold+Winged+figure+trophy+design+rear.jpg"
      cover: true
    - fileName: "Making_2_Patrick_Laing_Film_Award.jpg"
    - fileName: "Making_3_Patrick_Laing_Film_Award.jpg"
      cover: true
    - fileName: "O2O2-Side-Large-Patrick-Laing.jpg"
      cover: true
    - fileName: "Pinhole_Making.jpg"
      cover: true
    - fileName: "Plume-Outdoor-Unfurl-Brick.jpg"
    - fileName: "SNV37449.jpg"
    - fileName: "The_Flying_Skirt_TEST.jpg"
    - fileName: "Trophy_scans_1.jpg"
      cover: true
    - fileName: "Trophy_scans_2.jpg"
      cover: true
right:
  title: "Rings"
  videos:
    - 'https://player.vimeo.com/external/352805739.hd.mp4?s=0c6b42dee1f0d8264fed4047423e0303bea28094&profile_id=174'
  images:
    - fileName: 'surface_0003.jpg'
    - fileName: 'surface_0002.jpg'
    - fileName: 'surface_0001.jpg'
    - fileName: 'surface_0000.jpg'

contact:
  linkText: "Contact"
  email: "patrick@patricklaing.com"

credits:
  -
    linkText: "Design by Ongoing Projects"
    linkDestination: "https://ongoingprojects.co"
  -
    linkText: "Built by Laura Brown"
    linkDestination: "https://laurabrown.xyz"

